server:
  port: 8090

spring:
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        instance-host: 127.0.0.1
        instance-port: ${server.port}
  application:
    name: test-provider
logging:
  level:
    root : info
